# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:auth:
    desc: Run the auth service
    cmds:
      - go run cmd/auth-svc/main.go
    silent: true
