# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

dotenv:
  - .env

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:auth:
    desc: Run the auth service
    dir: cmd/auth-svc
    dotenv:
      - .env
    cmds:
      - |
        echo "Starting the auth service"
        PORT=8080 go run main.go
    silent: true

  db:migrate:
    desc: Run Database migrations
    cmds:
      - goose -dir migrations postgres "$DATABASE_URL" up

  goose:down:
    desc: goose down operation (bring down all the migrations)
    cmds:
      - goose -dir migrations postgres "$DATABASE_URL" down
    silent: true

  run:gateway:
    desc: Run the API gateway
    dir: cmd/api-gateway
    dotenv:
      - .env
    cmds:
      - |
        echo "starting the API gateway"
        PORT=3000 go run main.go 
    silent: true

  protoc:
    desc: generate stubs from proto definition
    cmds:
      - |
        protoc --go_out=gen \
        --proto_path=proto \
        --go_opt=paths=source_relative \
        --go-grpc_out=gen \
        --go-grpc_opt=paths=source_relative \
        proto/ingestion/v1/ingestion.proto
    silent: true
