// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	EventID       pgtype.UUID        `db:"event_id" json:"event_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Source        string             `db:"source" json:"source"`
	Version       string             `db:"version" json:"version"`
	Timestamp     pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	CorrelationID pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Payload       []byte             `db:"payload" json:"payload"`
	Status        string             `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	ErrorMessage  pgtype.Text        `db:"error_message" json:"error_message"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
