// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    event_id,
    event_type,
    source,
    version,
    timestamp,
    correlation_id,
    metadata,
    payload,
    status,
    error_message
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    'pending',
    ''
)
RETURNING event_id, event_type, source, version, timestamp, correlation_id, metadata, payload, status, created_at, processed_at, error_message
`

type CreateOutboxEventParams struct {
	EventID       pgtype.UUID        `db:"event_id" json:"event_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Source        string             `db:"source" json:"source"`
	Version       string             `db:"version" json:"version"`
	Timestamp     pgtype.Timestamptz `db:"timestamp" json:"timestamp"`
	CorrelationID pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Payload       []byte             `db:"payload" json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.EventID,
		arg.EventType,
		arg.Source,
		arg.Version,
		arg.Timestamp,
		arg.CorrelationID,
		arg.Metadata,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.EventID,
		&i.EventType,
		&i.Source,
		&i.Version,
		&i.Timestamp,
		&i.CorrelationID,
		&i.Metadata,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getOutboxEventByEventID = `-- name: GetOutboxEventByEventID :one
SELECT event_id, event_type, source, version, timestamp, correlation_id, metadata, payload, status, created_at, processed_at, error_message
FROM outbox_events
WHERE event_id = $1
`

func (q *Queries) GetOutboxEventByEventID(ctx context.Context, eventID pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEventByEventID, eventID)
	var i OutboxEvent
	err := row.Scan(
		&i.EventID,
		&i.EventType,
		&i.Source,
		&i.Version,
		&i.Timestamp,
		&i.CorrelationID,
		&i.Metadata,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT event_id, event_type, source, version, timestamp, correlation_id, metadata, payload, status, created_at, processed_at, error_message
FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
OFFSET $2
`

type GetPendingOutboxEventsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, arg GetPendingOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.Source,
			&i.Version,
			&i.Timestamp,
			&i.CorrelationID,
			&i.Metadata,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET
    status = 'failed',
    error_message = $2
WHERE event_id = $1
`

type MarkOutboxEventFailedParams struct {
	EventID      pgtype.UUID `db:"event_id" json:"event_id"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.EventID, arg.ErrorMessage)
	return err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET
  status = 'done',
  processed_at = NOW()
WHERE event_id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, eventID)
	return err
}
